baseurl = "/"
title = "Sets of Stats"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Tom Carmichael"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
	
	
	
	
	
	
[Author]
    name = "Tom Carmichael"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Sets of Stats"
    description = "Data stories on Australian sports"
    github = "https://github.com/tommycarmichael"
    linkedin = "https://www.linkedin.com/in/thomas-carmichael-b0761242/"
    twitter = "https://twitter.com/StatsTommy"
    email = "thomaslcarmichael@gmail.com"
    opengraph = true
    shareTwitter = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
